name: Fly Deploy Frontend

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy frontend
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build?
        run: |
          cd frontend
          npm i
          npm run build
