name: Fly Deploy Frontend

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy frontend
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: build?
        run: |
          cd frontend
          npm i
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
          single-commit: true
