name: Fly Deploy Frontend

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy frontend
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t southclaws/openmp-frontend -f Dockerfile.frontend .
